### PR TITLE
Ft user logout #167730635

### PR DESCRIPTION
**Pull request by coolbop1**
#### What does this PR do?
Logout functionality
#### Description of Task to be completed?
* **create get token middleware**
* **create verify token middleware**
* **connect to the database**
* **send extracted token to black list table**
#### How should this be manually tested?
By using postman and ensuring connection to the database locally
#### Any background context you want to provide?
Your reviews will be appreciated and worked on

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Good morning @coolbop1 I can see you have prepared SQL statements and some other things going on. Please can you kindly work me through what you did?

**Review by danoseun — COMMENTED** [review]
Good morning @coolbop1  I can see you have prepared SQL statements and some other things going on. Please can you kindly work me through what you did?

**Review by Kaytbode — CHANGES_REQUESTED** [review]
@coolbop1 Nice one!

- Noticed you added a **getPool** object to the **_src/config/config.js_**. Is that necessary for **sequelize** to connect to the database?
- in **_src/controllers/index.js_** I suggest you use template strings, as they are more elegant than strings concactenation.
- Noticed you created a **blacklists** table to store expired tokens. Why is it important we store tokens in the database?

**Comment by coolbop1** [comment]
@Kaytbode thanks for the feed back, the `blacklist` table is not meant for expired token, on the contrary, it is used to store active token that the user deliberately logged out, so the aim is for all other operations to have a kind of middleware that check if the token they are getting from the request is not in the blacklisted table, i.e logged out ,before moving to the next stage. 
If you thinks of a better way, kindly relate , lets see how to implement it.

**Comment by coolbop1** [comment]
@danoseun , I used  prepared statement in the controller so that another endpoint can use that same connection to the db and it is safer to use prepared  query for security reasons.

**Comment by Kaytbode** [comment]
> @Kaytbode thanks for the feed back, the `blacklist` table is not meant for expired token, on the contrary, it is used to store active token that the user deliberately logged out, so the aim is for all other operations to have a kind of middleware that check if the token they are getting from the request is not in the blacklisted table, i.e logged out ,before moving to the next stage.
> If you thinks of a better way, kindly relate , lets see how to implement it.

Gone through your story on Pivotal tracker, and it seems the task is meant to be **frontend** based on its description. This implementation will require you check for **token invalidation for every authentication**, which i feel might increase load on the database as users continue to grow.

I was going to propose we just reduce the expiry on the token, and implement logout frontend, but since you have gone that route, we'll might just stick with it.

How about the **getPool** object in the **_src/config/config.js_**?

**Comment by coolbop1** [comment]
@Kaytbode  i have used sequelize, please check it out and approve, thanks

**Review by chuksjoe — COMMENTED** [review]
Well done bro. Let's await the signup task.

**Review by Kaytbode — APPROVED** [review]

**Review by danoseun — APPROVED** [review]

**Review by Marshalheri — COMMENTED** [review]
Nice job. So i just want to point out in src/index.js we agreed it should not be **_app.use("/api/v1", routes)_** as i proposed earlier but it should be just **app.use("/api", routes)** since we wunt be using version for the API.
Well done bro.

**Review by chuksjoe — APPROVED** [review]
Well done brother @coolbop1

**Review by ChidiChuks — APPROVED** [review]
Nice work Bidemi!

**Comment by coolbop1** [comment]
Thanks guys

**Pull request merged**
