### PR TITLE
#167730646 Users should be able to comment on Travel requests

### PR DESCRIPTION
**Pull request by chuksjoe**
#### What does this PR do?
Add the functionality which allows a user or the manager to comment on a travel request
#### Description of Task to be completed?

- add model and migration files for the comments table
- write the logic that enables a user or a manager to comment on a travel request
- validate the travel_id, email and comment supplied by the user
- write tests for the POST and GET request endpoints.
- fix indentation and style violation problems in all the files on the codebase
- add the `.editorconfig` file that helps all team members to have a consistent coding style

#### How should this be manually tested?

- clone this repo into your local machine
- create a `.env` file in the root folder and copy the variables in the `.env.sample` into it, with their appropriate values
- run `npm install` then `npm test`

#### What are the relevant pivotal tracker stories?

[#167730646](https://www.pivotaltracker.com/story/show/167730646)

#### Questions:

### CODE REVIEW

**Review by Marshalheri — APPROVED** [review]
Nice work from what i have seen, but i will suggest you;
- The **confirmUserEmail** function which returns user fullname in the userMiddleware file should be rename to maybe **getUserFullNmae** since we have a function already that checks for user email which you referenced in there.
- Also in the src/index file the `routes(prefix, app);` should come after the base `app.all('/')`, just as a suggestion for orderliness anyway.

Well done bro!!!

**Comment by Kaytbode** [comment]
@chuksjoe  You really did a good job!

Just need some clarifications from you

By the way, why did you have to go through the **53 files** to enforce style formatting, when we already have an **eslint configuration (airbnb style guide) set up**? **Hound** is also configured on the repo to ensure the style guide is adhered to.

Noticed in your .eslintrc file, that you added _parser: babel-eslint_? are there any _experimental features_ we are using that eslint does not support?

In `commentControllers.js`, you are getting **user details (email, full name)** from `req.body`? Are users supposed to fill in those parameters before making comments? Don't you think, it is safer, and better to get those details through the token?

**Comment by chuksjoe** [comment]
> @chuksjoe You really did a good job!
> 
> Just need some clarifications from you
> 
> By the way, why did you have to go through the **53 files** to enforce style formatting, when we already have an **eslint configuration (airbnb style guide) set up**? **Hound** is also configured on the repo to ensure the style guide is adhered to.
> 
> Noticed in your .eslintrc file, that you added _parser: babel-eslint_? are there any _experimental features_ we are using that eslint does not support?
> 
> In `commentControllers.js`, you are getting **user details (email, full name)** from `req.body`? Are users supposed to fill in those parameters before making comments? Don't you think, it is safer, and better to get those details through the token?

Good morning @Kaytbode. Thanks for taking out time to go through my PR.

- Virtually all the files on our code base have one eslint violation or the other, and some persons text editor has other plugins like prettier that comes with its own styling guide, and this also affected most of the files. After I added the `.editorconfig`, I had to adjust most of the files to avoid the Hound-CI violation.
- The `async... await`, `spread operator` and the likes which are introduced in ES6+ are usually reported by eslint as `Unexpected token`. The `babel-eslint` is a parser module that helps eslint to be able to parse these newer javascript features and also avoid violating `Hound-CI` checks.
- The full name is actually gotten from querying the database in `src/middlewares/userMiddlewares.js`. The information that is gotten from the body is just the user email and the comment. Maybe I should have gotten the email from the token. This is quite thoughtful of you bro.

**Comment by chuksjoe** [comment]
> Nice work from what i have seen, but i will suggest you;
> 
> * The **confirmUserEmail** function which returns user fullname in the userMiddleware file should be rename to maybe **getUserFullNmae** since we have a function already that checks for user email which you referenced in there.
> * Also in the src/index file the `routes(prefix, app);` should come after the base `app.all('/')`, just as a suggestion for orderliness anyway.
> 
> Well done bro!!!

Good morning @Marshalheri, it's great having you review my PR.

- The function `findUserByEmail` which I referenced in the `src/middlewares/userMiddlewares.js` file does not handle the errors. It only queries the database to get the user's details and throws an error only when there is a network issue or the database is inaccessible. But the `confirmUserEmail` function returns an error if the user's email is not found, and also extracts the user first_name and last_name from the user object gotten from the database, then returns the full name in the `request body`.
- The root routes are usually come last after other routes. Maybe because they could serve as fallback routes, so in case the intended route is not reached.

**Comment by danoseun** [comment]
Nice job bro but how come you have this much changes?

**Review by captainamiedi — COMMENTED** [review]
i pull the branch and i checked the PT board. i initially had issue using the branch. i try to use postman to test but i keep getting error stating only "only letters are allowed". so i couldnt get pass the validations. 

7 commit in one PR i think its too much.

**Pull request closed without merging**
