### PR TITLE
#167730628 On successful registration, create JWT token

### PR DESCRIPTION
**Pull request by ChidiChuks**
#### What does this PR do?
- Have JSON-Web-Token create a token on every successful registration of new users
#### Description of Task to be completed?
- Users once registered via the registration endpoint, should receive a JWT to be required on all subsequent calls to all other endpoints that require authentication.
- Installing dependencies
- Creating JWT secret
- Creating payloads
- Setting up the signup mutations
- Adding the user to the context
#### How should this be manually tested?
- After cloning the repo, cd into the back-end `src` and RUN on terminal `npm run dev` using postman try to test this endpoint with post `http://localhost:3000/api/v1/auth/signup` and migrate to the `body` and insert values into this properties `first_name, last_name, email, password`
- For testing, RUN on terminal `npm test` or `npm run test`
#### Any background context you want to provide?
- There are implementations of dependencies on `authServices` to enable smooth accessibility such as; `regenerator-runtime` and `core-js`
#### What are the relevant pivotal tracker stories?
[#167730628](https://www.pivotaltracker.com/story/show/167730628)
#### Screenshots (if appropriate)
image

#### Questions:

### CODE REVIEW

**Comment by danoseun** [comment]
@ChidiChuks Which help do you need?

**Review by chuksjoe — APPROVED** [review]
well done bro.

**Comment by ChidiChuks** [comment]
> @ChidiChuks Which help do you need?

@danoseun Thanks for reaching out. I posted on the slack channel and got a lot of feedback. Most especially from @chuksjoe

**Comment by ChidiChuks** [comment]
> well done bro.

Thanks @chuksjoe and I appreciate

**Review by t4christ — APPROVED** [review]
Nice work chidi

**Review by coolbop1 — APPROVED** [review]

**Review by luqmanoop — COMMENTED** [review]
Why are you sending the user's (hashed) password back in the response?

**Comment by ChidiChuks** [comment]
> Why are you sending the user's (hashed) password back in the response?

Oh. thanks @codeshifu I will revert

**Comment by ChidiChuks** [comment]
> Why are you sending the user's (hashed) password back in the response?

I have deleted the hashed password and shown token in response

**Pull request merged**
