### PR TITLE
ft(return-trip-request): implement return trip controller.

### PR DESCRIPTION
**Pull request by Marshalheri**
**What does this PR do?**

Adds an endpoint for users to make a return trip request

**Description**

-  Create a return trip model in the models dir and also adds its migration.
-  Modify the travelController.js to include the function to handle the request for creating a return trip.
-  Modify travelServices.js to include services to implement the functionality of the return trip controller.
-  Create validation for the return trip travel request route.
-  Create a route for the return trip travel request.

**How can this be manually tested**

- Clone the repo
- Run _npm install_ to install dependencies, setup database and run _npm run dev_
- Make a post request to **localhost:5000/api/v1/travel/returntrip** and pass in the values to make a return trip request

**Relevant Pivotal tracker stories**

#167730639

### CODE REVIEW

**Review by danoseun — CHANGES_REQUESTED** [review]
Nice work bro but looks like you still have merge conflict. Kindly fix that so I can approve the PR.

**Comment by Marshalheri** [comment]
> 
> 
> Nice work bro but looks like you still have merge conflict. Kindly fix that so I can approve the PR.

Thanks.
I think the files showing conflicts are to be merged into the develop branch because it is fine before i pushed

**Review by Kaytbode — CHANGES_REQUESTED** [review]
@Marshalheri  Nice work

why did you comment out the id in the almost all the seeders table?

The feedback i got from the TTL also applies to you... Hound is **_dancing with the stars_** in your PR...  and your code indentation is not consistent. The team agreed **2 spaces** for indentation.

**Comment by chuksjoe** [comment]
Good afternoon @Marshalheri, well-done for the effort you have put into this task. But I don't think 61 file changes and 12 commits is ideal. Please, kindly look into it.
You can also help point me to the files you worked on so I can check out what you've done so far.

**Comment by Marshalheri** [comment]
> 
> 
> @Marshalheri Nice work
> 
> why did you comment out the id in the almost all the seeders table?
> 
> The feedback i got from the TTL also applies to you... Hound is **_dancing with the stars_** in your PR... and your code indentation is not consistent. The team agreed **2 spaces** for indentation.

Thanks for your feed back bro.
Well i had to comment out those id values because once the data is seeded into the table it gets a serialized number which is ok and quite easier to work with than the one we had there hard coded.

Also about the line spacing and indentation i will need a better clarity on that. I will message you privately.
Thanks

**Comment by Marshalheri** [comment]
> 
> 
> Good afternoon @Marshalheri, well-done for the effort you have put into this task. But I don't think 61 file changes and 12 commits is ideal. Please, kindly look into it.
> You can also help point me to the files you worked on so I can check out what you've done so far.

Thanks for the feedback.
About the commits and file changes i got all that when i did a git rebase and had to fix all the merge conflicts my branch had with the current state of the develop.
I really don't understand how the files got to that and i have no idea what to do.

**Pull request closed without merging**
