### PR TITLE
#167966220 Setup codebase to use ES6 (with Babel support)

### PR DESCRIPTION
**Pull request by chuksjoe**
#### What does this PR do?
Setup babel for transpiling ES6 codes to ES5

#### Description of Task to be completed?

- install babel-cli and babel-preset-env for the transpilation
- add babelrc file for the babel configuration
- write a test to test some of the ES6 features
- change the codebase to ES6
- replace console.log with a debug module function

#### How should this be manually tested?

- clone the repo, then cd into the root directory
- run the following commands:
-- `npm install`
-- `npm test`
#### What are the relevant pivotal tracker stories?
[#167966220](https://www.pivotaltracker.com/story/show/167966220)

#### Questions:

### CODE REVIEW

**Review by Kaytbode — CHANGES_REQUESTED** [review]
I am really impressed at the speed at which you execute your assigned tasks, and such zeal motivates me.
However, concerning this PR, 
I suggest that we use the latest versions of  **babel**, and please communicate the reasons its use might not be possible for this application if there are any.
I also noticed you are using **babel-polyfill**, which has been **deprecated**. 
Here is an 
[alternative to babel-polyfill](https://babeljs.io/docs/en/babel-polyfill), or does the use of **babel-polyfill** add benefits to the application?

**Comment by ChidiChuks** [comment]
You did a great job here @chuksjoe. I like that you used babel 7. Installing babel-cli and babel-preset-env which are the most required installation process. I have reviewed this PR and I'm okay with it.

**Review by ChidiChuks — APPROVED** [review]

**Comment by chuksjoe** [comment]
@Kaytbode, the the one that is deprecated is @babel/polyfill which depends on the deprecated Babel module.
The old Babel model usually encompasses most of the other dependent modules such as the polyfill, transform, preset, etc. But it has been broken down such that a developer only installs the ones he/she needs.
Now the working Babel modules are `babel-cli` and `babel-core` of which you can use only one.
Then the other addons such as babel-polyfill which allows the usage of async await, promise, weakest and the likes. You can read more on the polyfill I used here: https://babeljs.io/docs/en/6.26.3/babel-polyfill

**Review by Kaytbode — COMMENTED** [review]
@chuksjoe You are right. **@babel/polyfill** and not **babel-polyfill** is the one that has been deprecated. However, you will not have to use **babel-polyfill** if you are using **babel-7**

**Comment by chuksjoe** [comment]
> @chuksjoe You are right. **@babel/polyfill** and not **babel-polyfill** is the one that has been deprecated. However, you will not have to use **babel-polyfill** if you are using **babel-7**

@Kaytbode, I have upgraded the babel to version 7.5.5 as we agreed. Please, do review it.

**Review by captainamiedi — COMMENTED** [review]
i think you should add script for production because nodemon will be save on devDependencies. so it will crash on heroku.

**Comment by chuksjoe** [comment]
> i think you should add script for production because nodemon will be save on devDependencies. so it will crash on heroku.

I will work on that. But mind you, Heroku will require a Procfile.

**Comment by captainamiedi** [comment]
Yeah. I'm aware of that. Nice job

**Comment by chuksjoe** [comment]
> Yeah. I'm aware of that. Nice job

@captainamiedi, you can check it out now. Thanks for the feedback.

**Review by Kaytbode — APPROVED** [review]
@chuksjoe  **Excellent!** 
hopefully it does not break anything... :)

**Comment by chuksjoe** [comment]
> @chuksjoe **Excellent!**
> hopefully it does not break anything... :)

Yes, for sure. thanks for your feedback @Kaytbode.

**Review by captainamiedi — APPROVED** [review]

**Review by danoseun — COMMENTED** [review]
Nice job bro. Why did you use `set DEBUG=...` in the dev script? Is that command particular to an OS?

**Comment by captainamiedi** [comment]
it's not doing anything special. it helps to debug your work as it console
error with different colours and it aids when doing proper debugging. using
SET makes it compatible with Windows wish most of us are using. not
something to work about. it just console. log with different colours.

**Pull request merged**
