### PR TITLE
Ft socialmedia login #167730632

### PR DESCRIPTION
**Pull request by Kaytbode**
**What does this PR do?**
Users can login with facebook and google accounts

**Description of Task to be completed?**
Users should be able to login with facebook and google accounts

**How should this be manually tested?**

- Login to your facebook account,
- At the terminal type **_npm run dev_**
- Open your browser to view **api response** on localhost at your specified port

What are the relevant pivotal tracker stories?
#167730632

### CODE REVIEW

**Review by danoseun — COMMENTED** [review]
Looks like you have done a nice job bro but I will have to look at this code properly to understand what you have done.

**Comment by Marshalheri** [comment]
Nice job team mate.
So i looked through the code and its cool. 
I am proposing a folder structure which i implemented for the routes which is **/routes/api/v1/routerV1.js**
Probably you could look it up in ft-login branch and see if it can be implemented in your own work.
Thanks

**Review by chuksjoe — COMMENTED** [review]
Nice job brother @Kaytbode, but some of the modules you imported in the entry file (`src/index.js`) such as body-parser, errorHandler, and session were removed earlier as they were not relevant. It seems like you did not pull the current code on our remote codebase before you started working on this feature.

**Comment by Kaytbode** [comment]
@Marshalheri  Thanks 

hmmn... as regards your proposed /routes/api/v1/routerV1.js


> Nice job brother @Kaytbode, but some of the modules you imported in the entry file (`src/index.js`) such as body-parser, errorHandler, and session were removed earlier as they were not relevant. It seems like you did not pull the current code on our remote codebase before you started working on this feature.

Thanks for the feedback. I actually did pull from the **codebase** else i would have had a merge conflict. 
I installed **_body-parser_** cause it is needed to view response from the `req.body`, while using **Postman**.

**Comment by Kaytbode** [comment]
> Nice job brother @Kaytbode, but some of the modules you imported in the entry file (`src/index.js`) such as body-parser, errorHandler, and session were removed earlier as they were not relevant. It seems like you did not pull the current code on our remote codebase before you started working on this feature.

Thanks for the feedback. I actually did pull from the **codebase** else i would have had a merge conflict.
I installed _body-parser_ cause it is needed to view response from the `req.body`, while using **Postman.**

**Review by danoseun — APPROVED** [review]

**Review by chuksjoe — CHANGES_REQUESTED** [review]
Well done bro @Kaytbode , this looks great. But here are some of my observations:
- the `.env.sample` file is not meant to contain the actual values but just the sample of variables that should be supplied in the environment, and you also do not need to add it to gitignore because it helps whoever that wants to run our application to know the values he/she should have in the actual .env file or for deploying on Heroku or testing on Travis.
- also, specifying sensitive information such as the secret keys for Facebook and Google in the Travis file is not ideal. You can forward those details to me so that I can add them in the environment variables section in our Travis settings online.
- also in the `src/index.js`, we are actually not using body-parser, errorhandle and the express-session modules. For the body-parser, express.js already has its own which is what we used. Obviously, in the course of you resolving merge conflict, you might have deleted some of those code. Kindly revert the changes in this file to what we currently have on the develop branch, then you can add your code snippets into it.

**Comment by Kaytbode** [comment]
> Well done bro @Kaytbode , this looks great. But here are some of my observations:
> 
> * the `.env.sample` file is not meant to contain the actual values but just the sample of variables that should be supplied in the environment, and you also do not need to add it to gitignore because it helps whoever that wants to run our application to know the values he/she should have in the actual .env file or for deploying on Heroku or testing on Travis.
> * also, specifying sensitive information such as the secret keys for Facebook and Google in the Travis file is not ideal. You can forward those details to me so that I can add them in the environment variables section in our Travis settings online.
> * also in the `src/index.js`, we are actually not using body-parser, errorhandle and the express-session modules. For the body-parser, express.js already has its own which is what we used. Obviously, in the course of you resolving merge conflict, you might have deleted some of those code. Kindly revert the changes in this file to what we currently have on the develop branch, then you can add your code snippets into it.

Thanks for the clarification
> Aware about the sensitive information part but could not wait to test my code. You have access to those information already, but will still forward it to you all the same.
> I have refactored my code and removed body-parser. However, you might need body-parser for postman

**Comment by Kaytbode** [comment]
@chuksjoe  sent the sensitive materials to you on slack.

please let me know when you have added it so that i can remove it from the travis.yml file.

Thanks

**Review by ChidiChuks — COMMENTED** [review]
You've done really well on this. But, however, I'll like to call your attention to a few blockers.

- update your local project with the new merge via `git pull`
- resolve conflicts on `src/controllers/authControllers.js`, `src/routes/api/authRoutes.js`, `src/tests/authTest.js`.

I guess that's all for now. Welldone bro

**Review by chuksjoe — APPROVED** [review]
Nice job my Team Lead. I wish you could have time to breeze me through the configuration process of this social media authentication. 👍👍

**Comment by Kaytbode** [comment]
> Nice job my Team Lead. I wish you could have time to breeze me through the configuration process of this social media authentication.

Thanks for the review

I will explain the process to you through slack

**Review by ChidiChuks — APPROVED** [review]
Great job Kayode! You deserve my approval. I'll also love you to send minimal documentation on slack to the PR. Well done.

**Review by iakhator — APPROVED** [review]

**Pull request merged**
