### PR TITLE
#167730616 Configure PostgreSQL as Database Engine

### PR DESCRIPTION
**Pull request by ChidiChuks**
#### What does this PR do?
Have PostgreSQL as the database engine for Barefoot Nomad

#### Description of Task to be completed?
Optimize PostgreSQL database engine for production-ready environments

#### How should this be manually tested?
After cloning the repo, open a package.json file in a code editor precisely VSCode and check for a block of code with an object name of `dependencies` to find two names `(pg and pg-hstore)`. Then check on `env.sample` to connect to the database

#### Any background context you want to provide?
- Adding postgresql configuration file
• Creating a pool
• Successfully creating the database [barefoot]
• Creating all the tables to be used in the models' folder
• Configuring the application to start the server with Sequelize properly integrated
• Bootstrapping the database folder by creating auto-generated boiler-plates
• Updating script files for easier run and update
• Creating the seeders' files to insert datas into the tables which could be ran with the script (npm run create:tables)

#### What are the relevant pivotal tracker stories?
[#167730616](https://www.pivotaltracker.com/story/show/167730616)

#### Screenshots (if appropriate)
image

#### Questions:

### CODE REVIEW

**Review by luqmanoop — COMMENTED** [review]
Is this PR a WIP (work in progress) or it's ready?

**Comment by ChidiChuks** [comment]
The PR is now ready for merge. Thanks for the comment.

**Review by luqmanoop — CHANGES_REQUESTED** [review]
@ChidiChuks Good job but this PR barely does anything. You were asked to configure a Postgres database, I don't see how installing a few npm packages will automatically set up the connection

**Review by Kaytbode — CHANGES_REQUESTED** [review]
@ChidiChuks  Well done.
I feel you are required to create a database for the project, and store the access properties of the 
database in environment variables.

**Comment by ChidiChuks** [comment]
Okay @codeshifu . I just want to ask ... am I suppose to create the connection string like the [.env file and config.js]?
Thank you.

**Comment by ChidiChuks** [comment]
> @ChidiChuks Well done.
> I feel you are required to create a database for the project, and store the access properties of the
> database in environment variables.

Thanks @Kaytbode  I guess creating the database is meant to be under the sequelize chore. Because that's the reason why we are using sequelize. for example [createdb and sequelize db:migrate, etc] all this are part of the sequelize functionality.

But I think my job isn't complete yet if I'm to take a closer look cos I have to maybe create the [.env] file and following the folder structure also create a config.js file to interact.

**Comment by Kaytbode** [comment]
@ChidiChuks .. You are probably right, but

based on my understanding of this task,  **Sequelize** is the database _ORM_ that supposed to connect the database  to the application, if given the _**database url,**_ or **_database configurations_**.

**Comment by ChidiChuks** [comment]
@Kaytbode I think you're also correct with some observations. Most especially the **database url**, and **database configs** which I really didn't understand what I was thinking about before saying I'm finished. I'm working on them now. Thanks a lot!

**Review by captainamiedi — CHANGES_REQUESTED** [review]
i think you have to setup the enivronment for testing, production and development.
you can still also create the configure for the database like Sequelize(process.env[config.use_env_variable]).
when using process enivronment, please follow what we have on the .env.sample because that is what everybody might work with.

**Comment by ChidiChuks** [comment]
@captainamiedi I understand what you're saying but the .env file is one that will be simultaneously determined by my chore and also setting up an environment for both test, prod and dev can be done on a single module export code-block. A better way to the cleaner codebase. Thanks for your comment.

**Comment by captainamiedi** [comment]
you can do it on a single block is just to check if it dev environment,
test environment and prod environment. thanks

**Review by chuksjoe — CHANGES_REQUESTED** [review]
Nice job man @ChidiChuks.
- I don't think you need to remove `.env.test` from .gitignore.
- `src/config/config.js` will likely be replaced with what will be generated by Sequelize, as such, you really don't need to insert any code into it. Likewise `src/config/config.js`.
- lastly, I don't think the changes to `src/index.js` is necessary.

I will suggest you wait for @coolbop1 to finish up with the Sequelize setup.

**Comment by ChidiChuks** [comment]
> Nice job man @ChidiChuks.
> 
> * I don't think you need to remove `.env.test` from .gitignore.
> * `src/config/config.js` will likely be replaced with what will be generated by Sequelize, as such, you really don't need to insert any code into it. Likewise `src/config/config.js`.
> * lastly, I don't think the changes to `src/index.js` is necessary.
> 
> I will suggest you wait for @coolbop1 to finish up with the Sequelize setup.

Thanks for your comment @chuksjoe . But, however, I think it is best to remove **.env.test** as we won't be using any file like that in the project. Since I worked on the **.env** file. I should be able to know that it won't be necessary as the .env file will be used for testing. Also, @coolbop1 is meant to continue from where I stopped which means my chore is meant to be a guide for the Sequelize chore to be activated. Lastly, I feel it is necessary to make the change in the **'src/index.js'** as the description of chore says **'configuring PostgreSQL as a database engine'**. which also entails activating the entry point of the app.

**Comment by chuksjoe** [comment]
> > Nice job man @ChidiChuks.
> > 
> > * I don't think you need to remove `.env.test` from .gitignore.
> > * `src/config/config.js` will likely be replaced with what will be generated by Sequelize, as such, you really don't need to insert any code into it. Likewise `src/config/config.js`.
> > * lastly, I don't think the changes to `src/index.js` is necessary.
> > 
> > I will suggest you wait for @coolbop1 to finish up with the Sequelize setup.
> 
> Thanks for your comment @chuksjoe. But, however, I think it is best to remove **.env.test** as we won't be using any file like that in the project. Since I worked on the **.env** file. I should be able to know that it won't be necessary as the .env file will be used for testing. Also, @coolbop1 is meant to continue from where I stopped which means my chore is meant to be a guide for the Sequelize chore to be activated. Lastly, I feel it is necessary to make the change in the **src/index.js** as the description of chore says **'configuring PostgreSQL as a database engine'**. which also entails activating the entry point of the app.

@ChidiChuks, you will need the `.env.test` for your local testing before pushing the branch to the remote repo.
Also, I don't see how @coolbop1 will continue from your `src/config/config.js` setup when it's apparent that the files will be auto-generated.
For `src/index.js`. It contains some code snippets that are necessary for error management. The only changes I would have suggested in it is the removal of the Mongoose connection setup.

**Comment by ChidiChuks** [comment]
> > > Nice job man @ChidiChuks.
> > > 
> > > * I don't think you need to remove `.env.test` from .gitignore.
> > > * `src/config/config.js` will likely be replaced with what will be generated by Sequelize, as such, you really don't need to insert any code into it. Likewise `src/config/config.js`.
> > > * lastly, I don't think the changes to `src/index.js` is necessary.
> > > 
> > > I will suggest you wait for @coolbop1 to finish up with the Sequelize setup.
> > 
> > 
> > Thanks for your comment @chuksjoe. But, however, I think it is best to remove **.env.test** as we won't be using any file like that in the project. Since I worked on the **.env** file. I should be able to know that it won't be necessary as the .env file will be used for testing. Also, @coolbop1 is meant to continue from where I stopped which means my chore is meant to be a guide for the Sequelize chore to be activated. Lastly, I feel it is necessary to make the change in the **src/index.js** as the description of chore says **'configuring PostgreSQL as a database engine'**. which also entails activating the entry point of the app.
> 
> @ChidiChuks, you will need it for your local testing before pushing the branch to the remote repo

Hmm. @chuksjoe I don't see why I need a **.env.test** file when I already have my **.env** file. If this was for me to test on my local machine then I think I already have one **environment** file that has covered for both test, production and development. Since it serves as a utility

**Comment by ChidiChuks** [comment]
> > > Nice job man @ChidiChuks.
> > > 
> > > * I don't think you need to remove `.env.test` from .gitignore.
> > > * `src/config/config.js` will likely be replaced with what will be generated by Sequelize, as such, you really don't need to insert any code into it. Likewise `src/config/config.js`.
> > > * lastly, I don't think the changes to `src/index.js` is necessary.
> > > 
> > > I will suggest you wait for @coolbop1 to finish up with the Sequelize setup.
> > 
> > 
> > Thanks for your comment @chuksjoe. But, however, I think it is best to remove **.env.test** as we won't be using any file like that in the project. Since I worked on the **.env** file. I should be able to know that it won't be necessary as the .env file will be used for testing. Also, @coolbop1 is meant to continue from where I stopped which means my chore is meant to be a guide for the Sequelize chore to be activated. Lastly, I feel it is necessary to make the change in the **src/index.js** as the description of chore says **'configuring PostgreSQL as a database engine'**. which also entails activating the entry point of the app.
> 
> @ChidiChuks, you will need the `.env.test` for your local testing before pushing the branch to the remote repo.
> Also, I don't see how @coolbop1 will continue from your `src/config/config.js` setup when it's apparent that the files will be auto-generated.
> For `src/index.js`. It contains some code snippets that are necessary for error management. The only changes I would have suggested in it is the removal of the Mongoose connection setup.

@chuksjoe for me I think those error handling will be done by anyone assigned the task of Test Driven Development. The first step is to have a serene environment of the codebase and then develop from there. That's why it's called **configuration**. Also, @coolbop1 is working on an ORM [Sequelize] which should interface with my chore [Postgres]. Postgres is the database and without the **database,** there is no place for an **ORM(Object Relational Mapping)** to interact.

**Review by danoseun — COMMENTED** [review]
@ChidiChuks You have really done some work. Has the `npm start` error been fixed now also you said something about having an error with foreign keys, where would that be?

**Review by chuksjoe — CHANGES_REQUESTED** [review]
Nice work bro @chidi, but there some areas I will like to draw your attention to:
- in `src/database/models/index.js` on line 3 where you defined the Sequelize object, using the database variables that worked on your locally installed Postgres will not work for production and for testing. So you should use the database `config.js` env variables that are passed to it via the NODE_ENV object.
- in `src/index.js` on line 82, setting the force to true will always create new tables whenever the app is ran, as such the data stored in the production database will never be persistent. I will suggest you remove the force property from the sync method.

**Comment by Marshalheri** [comment]
i wish to state that the model for user should be singular i.e **user** and not users.
Also i noticed you did not set the password not to allow null, i dont know if that is also obtainable during the user signup

**Comment by ChidiChuks** [comment]
> i wish to state that the model for user should be singular i.e **user** and not users.
> Also i noticed you did not set the password not to allow null, i dont know if that is also obtainable during the user signup

Thanks @Marshalheri for your comment. This has been corrected and so instead of having **users** as the naming convention we now have singular names as **user**, **travel**, etc...

**Comment by ChidiChuks** [comment]
> Nice work bro @chidi, but there some areas I will like to draw your attention to:
> 
> * in `src/database/models/index.js` on line 3 where you defined the Sequelize object, using the database variables that worked on your locally installed Postgres will not work for production and for testing. So you should use the database `config.js` env variables that are passed to it via the NODE_ENV object.
> * in `src/index.js` on line 82, setting the force to true will always create new tables whenever the app is ran, as such the data stored in the production database will never be persistent. I will suggest you remove the force property from the sync method.

Thank you so much for your comment @chuksjoe. I have properly structured the chore in a way to accept variables from the .env file through **process.env** on the `config.js` and removed the `({ force: true })` sync method.

**Comment by ChidiChuks** [comment]
> @ChidiChuks You have really done some work. Has the `npm start` error been fixed now also you said something about having an error with foreign keys, where would that be?

Thanks @danoseun for your comment. The `npm start` error has been fixed and also the `association` to the foreign keys has been fixed also. Everything is fine and the tables/data can be fully accessed in the database through a  CLI [SQL Shel] or GUI [PG Admin 4].

**Review by chuksjoe — APPROVED** [review]
Well done bro @ChidiChuks, this one has my approval.

**Comment by Marshalheri** [comment]
Nice work team mate.

I want to point out that in the model for user i implemented a function to hash a password before the user is stored in the database.

You can look through it in my PR and see if its ok to be included in your own work. Thanks

**Comment by ChidiChuks** [comment]
> Nice work team mate.
> 
> I want to point out that in the model for user i implemented a function to hash a password before the user is stored in the database.
> 
> You can look through it in my PR and see if its ok to be included in your own work. Thanks

Thanks for the comment @Marshalheri but I think it will be nice to do it in my feature and not here in my chore. I'll implement it over there

**Review by coolbop1 — APPROVED** [review]
Nice job. moving forward

**Review by Kaytbode — CHANGES_REQUESTED** [review]
@ChidiChuks  Brilliant!

However, i have a few issues to raise

- Noticed you are using **module.export** instead of the **es6 export**?

- Some of your files still have the **es5 require** statements?

- The **user** table does not allow null as password, does that mean we will not be able to store _users logging in via social media_ into the database? I feel the password verification should implemented through the backend code, and not by the database.

**Comment by Marshalheri** [comment]
> 
> 
> > Nice work team mate.
> > I want to point out that in the model for user i implemented a function to hash a password before the user is stored in the database.
> > You can look through it in my PR and see if its ok to be included in your own work. Thanks
> 
> Thanks for the comment @Marshalheri but I think it will be nice to do it in my feature and not here in my chore. I'll implement it over there

So i guess what i implemented already should be left that way since you will implement it the same way in your own code base?

**Comment by Marshalheri** [comment]
> 
> 
> @ChidiChuks Brilliant!
> 
> However, i have a few issues to raise
> 
>     * Noticed you are using **module.export** instead of the **es6 export**?
> 
>     * Some of your files still have the **es5 require** statements?
> 
>     * The **user** table does not allow null as password, does that mean we will not be able to store _users logging in via social media_ into the database? I feel the password verification should implemented through the backend code, and not by the database.

You mean the password column should be made nullable?

**Comment by Marshalheri** [comment]
@ChidiChuks i also what to suggest that the column for is_active in the user migration file should have a default value of false unless we wunt be implementing user verification after signup is complete

**Review by Marshalheri — APPROVED** [review]
I have given all my comments so far and i am cool with the work so far. I approve.

**Comment by Kaytbode** [comment]
> > @ChidiChuks Brilliant!
> > However, i have a few issues to raise
> > ```
> > * Noticed you are using **module.export** instead of the **es6 export**?
> > 
> > * Some of your files still have the **es5 require** statements?
> > 
> > * The **user** table does not allow null as password, does that mean we will not be able to store _users logging in via social media_ into the database? I feel the password verification should implemented through the backend code, and not by the database.
> > ```
> 
> You mean the password column should be made nullable?

@Marshalheri Yes i suggest the password column on the database is nullable, except you have an alternative to add users logging in through social media to the database? I also suggested verifying the password field through the backend code.

**Comment by ChidiChuks** [comment]
> @ChidiChuks Brilliant!
> 
> However, i have a few issues to raise
> 
> * Noticed you are using **module.export** instead of the **es6 export**?
> * Some of your files still have the **es5 require** statements?
> * The **user** table does not allow null as password, does that mean we will not be able to store _users logging in via social media_ into the database? I feel the password verification should implemented through the backend code, and not by the database.

Thanks, @Kaytbode for your comment. But, Sequelize uses es5 because it is passing through babel as the transpiler. So, files with the **es5 code blocks** are passing through Babel and so it's more to our advantage from avoiding a break in the app. For the **user** not allowing password. I feel it will be updated in my new task in the **Sign up  JWT feature**. But thanks for your comment and observation.

**Review by luqmanoop — COMMENTED** [review]
Why is this PR doing other than configuring the Postgres database?

**Pull request merged**
