### PR TITLE
Ft user login #167730631

### PR DESCRIPTION
**Pull request by Marshalheri**
**What this PR does**
This PR implements the functionality for user signin using email and password

**Tasks completed**
- create a route for user signin
- create signin controller and implement its functions inside authController.js file
- create helper functions in authService.js file
- create utility functions in utils directory
- create middleware functions for the controller
- add test in authRoute test file to test the user authentication route is working as required

**How can this be manually tested**
Go to github.com https://github.com/andela/archangel-backend/
Clone the repo to your local system
Install dependencies, setup database and run npm start:dev in the terminal
Using postman or any http request tool, make a post request to /api/v1/auth/login

**What are the relevant pivotal tracker stories?**
[#167730631]

### CODE REVIEW

**Comment by coolbop1** [comment]
Ok, i have seen it , and followed all the connections all the way to the  database/model folder, which i must confess is a very brilliant idea, but just a suggestion, wouldn't it be simpler if you query the db  directly from the services folder and return and object containing the user's info if the credentials match, i am only suggesting, if there if a reason you did it this way, let us know and i would be glad to approve. good job

**Comment by Marshalheri** [comment]
> 
> 
> Ok, i have seen it , and followed all the connections all the way to the database/model folder, which i must confess is a very brilliant idea, but just a suggestion, wouldn't it be simpler if you query the db directly from the services folder and return and object containing the user's info if the credentials match, i am only suggesting, if there if a reason you did it this way, let us know and i would be glad to approve. good job

So during the standup i got to understand that i shouldn't alter the folder structure so i guess i will have to refactor that for my next commit.
But by **" wouldn't it be simpler if you query the db directly from the services folder and return and object containing the user's info if the credentials match,"** are you reffering to the login logic?

**Review by chuksjoe — COMMENTED** [review]
Nice work bro @Marshalheri. These are some of my observations and suggestions:

- instead of `src/controllers/loginController.js`, we will likely be having `src/controllers/authController.js` where all the authentication controller such as signup, signin/login, passwordReset, logout and the social media signup/signin functions will be called from.

- in `src/index.js` there is already an import statement for the routes on line 13. Also, we won't be versioning the app, as such the code on line 37 is not necessary.

- all the routes will be accessed via the index file in the route folder, such that authRoute.js will handle only authentication routes, userRoute.js will handle all user manipulation routes, so also for travels and accommodations.

- just as I noted for `src/controllers/loginController.js`, so also it goes for `src/services/loginServices.js`. Also, it's not ideal having multiple exports in a single file unless it's unavoidable. So you can export an object with all the functions defined in it.

- instead of `src/utils/generateToken.js`, we should have a file called `src/utils/authUtils.js` that holds all utility functions used for authentication.

- for `src/utils/messages.js`, `src/utils/response.js` and `src/utils/statusCode.js`, I will suggest you use this structure:
```
export default {
	welcome: 'Welcome to Archangel Barefoot Nomad Web App API.',
	response: (res, status, resStatusMessage, data) => res.status(status).json({
  		status: resStatusMessage,
  		data
	}),
	success: 200,
};
```
instead of defining with const, then exporting.

Nice job so far brother.

**Comment by Marshalheri** [comment]
> 
> 
> Nice work bro @Marshalheri. These are some of my observations and suggestions:
> 
>     * instead of `src/controllers/loginController.js`, we will likely be having `src/controllers/authController.js` where all the authentication controller such as signup, signin/login, passwordReset, logout and the social media signup/signin functions will be called from.
> 
>     * in `src/index.js` there is already an import statement for the routes on line 13. Also, we won't be versioning the app, as such the code on line 37 is not necessary.
> 
>     * all the routes will be accessed via the index file in the route folder, such that authRoute.js will handle only authentication routes, userRoute.js will handle all user manipulation routes, so also for travels and accommodations.
> 
>     * just as I noted for `src/controllers/loginController.js`, so also it goes for `src/services/loginServices.js`. Also, it's not ideal having multiple exports in a single file unless it's unavoidable. So you can export an object with all the functions defined in it.
> 
>     * instead of `src/utils/generateToken.js`, we should have a file called `src/utils/authUtils.js` that holds all utility functions used for authentication.
> 
>     * for `src/utils/messages.js`, `src/utils/response.js` and `src/utils/statusCode.js`, I will suggest you use this structure:
> 
> 
> ```
> export default {
> 	welcome: 'Welcome to Archangel Barefoot Nomad Web App API.',
> 	response: (res, status, resStatusMessage, data) => res.status(status).json({
>   		status: resStatusMessage,
>   		data
> 	}),
> 	success: 200,
> };
> ```
> 
> instead of defining with const, then exporting.
> 
> Nice job so far brother.

Thanks for the detailed feedback so far.
i will work on refactoring them and put in place all you suggested.
Best regards

**Review by danoseun — COMMENTED** [review]
God morning @Marshalheri Quick questions: 
1. Are you supposed to implement jwt?
2. Did you create models of your own again?
Also remember that we won't be versioning in this project and the standard for naming environment variables is *PORT* over *port*. You have done a nice job bro.

**Review by chuksjoe — CHANGES_REQUESTED** [review]
Nice work bro @Marshalheri, but it seems you are having too many duplicate files. These are my observations and suggestions:

- some contents of `src/utils/messages.js` are already in `src/utils/messageUtils.js`. I will suggest you move the messages for your feature into `src/utils/messageUtils.js`.
- the function in `src/utils/generateToken.js` is already defined in `src/middlewares/tokenMiddleware.js` file which is the appropriate file for it.
- the file `src/utils/errorClass.js` contains the same class definition in `src/utils/ApiErrors.js`. Though, it's more appropriate to assign to a file the name of the class defined therein.
- the authentication service functions in `src/services/loginServices.js` file are already defined in the `src/services/authServices.js` file.
- the files `src/routes/api/v1/routesV1.js`, `src/routes/api/auth.js` and `src/routes/api/routes.js` seems irrelevant as the files `src/routes/api/authRoutes.js` and `src/routes/api/index.js` has taken care of the routing functions.
- the file `src/controllers/loginController.js` contains a function that is already defined in `src/controllers/authControllers.js`.

Great effort you must have put into this work I believe. Please, kindly look into this bro, and keep up the good work.

**Comment by Marshalheri** [comment]
> Nice work bro @Marshalheri, but it seems you are having too many duplicate files. These are my observations and suggestions:
> 
> * some contents of `src/utils/messages.js` are already in `src/utils/messageUtils.js`. I will suggest you move the messages for your feature into `src/utils/messageUtils.js`.
> * the function in `src/utils/generateToken.js` is already defined in `src/middlewares/tokenMiddleware.js` file which is the appropriate file for it.
> * the file `src/utils/errorClass.js` contains the same class definition in `src/utils/ApiErrors.js`. Though, it's more appropriate to assign to a file the name of the class defined therein.
> * the authentication service functions in `src/services/loginServices.js` file are already defined in the `src/services/authServices.js` file.
> * the files `src/routes/api/v1/routesV1.js`, `src/routes/api/auth.js` and `src/routes/api/routes.js` seems irrelevant as the files `src/routes/api/authRoutes.js` and `src/routes/api/index.js` has taken care of the routing functions.
> * the file `src/controllers/loginController.js` contains a function that is already defined in `src/controllers/authControllers.js`.
> 
> Great effort you must have put into this work I believe. Please, kindly look into this bro, and keep up the good work.

Oh.
Thanks about this i did these cleanup before i guess they came back when i did a rebase let me clean them up now and commit again.
Thanks

**Review by chuksjoe — APPROVED** [review]
Nice job bro @Marshalheri, well done.

**Review by iakhator — DISMISSED** [review]
What is this PR?

**Comment by Marshalheri** [comment]
> What is this PR?

Good evening.

I have updated it. It is no longer a WIP.
Please treat.
Thanks

**Review by ChidiChuks — APPROVED** [review]
Great job  brother

**Pull request merged**
