### PR TITLE
#167730646 Users should be able to comment on Travel requests

### PR DESCRIPTION
**Pull request by chuksjoe**
#### What does this PR do?
Add the functionality which allows a user or the manager to comment on a travel request
#### Description of Task to be completed?

- add model and migration files for the comments table
- write the logic that enables a user or a manager to comment on a travel request
- validate the travel_id, email and comment supplied by the user
- write tests for the POST and GET request endpoints.

#### How should this be manually tested?

- clone this repo into your local machine
- create a `.env` file in the root folder and copy the variables in the `.env.sample` into it, with their appropriate values
- run `npm install` then `npm test`

#### What are the relevant pivotal tracker stories?

[#167730646](https://www.pivotaltracker.com/story/show/167730646)

#### Questions:

### CODE REVIEW

**Review by t4christ — COMMENTED** [review]
NIce one chuks.

**Review by t4christ — APPROVED** [review]

**Review by captainamiedi — APPROVED** [review]
PR is tested and all functions are working fine. 
functions are inline with story on the PT board.
2 commits on a PR is a nice one as well.

**Comment by Kaytbode** [comment]
@chuksjoe  very good job

Although, you still chose not to get user data from token..

**Review by Kaytbode — APPROVED** [review]

**Comment by chuksjoe** [comment]
> @chuksjoe very good job
> 
> Although, you still chose not to get user data from token..

Thanks for taking out time to review my PR. I actually did get the user's data from the token. You can check out the middleware function that I defined in `userMiddlewares` in the middlewares folder.

**Review by iakhator — APPROVED** [review]

**Pull request merged**
