### PR TITLE
#167730618 configuration of Eslint

### PR DESCRIPTION
**Pull request by captainamiedi**
#### What does this PR do?

- configuring of Eslint

#### Description of Task to be completed?

- having Eslint working

#### How should this be manually tested?

- Eslint was tested manually

#### Any background context you want to provide?

-  ESLint covers both code quality and coding style issues. ESLint supports current standards of ECMAScript, and experimental syntax from drafts for future standards.

#### What are the relevant pivotal tracker stories?

- #167730618

#### Questions:

### CODE REVIEW

**Comment by chuksjoe** [comment]
- well done bro. But I thought in the Pivotal Tracker the style guide configuration was specified.

- Also, I don't think we'll be needing the eslint-plugin-react and eslint-plugin-react-hook for this backend project as that will be done in the frontend repo.

- Finally, I will suggest you us .json instead of .js extension for the .eslintrc file as it is the default extension and its easier to work.

**Review by luqmanoop — CHANGES_REQUESTED** [review]
@captainamiedi good job. However, this PR doesn't meet the set requirements on the board. Go back and check in the description of the ticket/story.

**Comment by captainamiedi** [comment]
thanks for your observation. i will look into it

**Comment by captainamiedi** [comment]
good morning. changed has been made and push as well

**Pull request merged**
