### PR TITLE
#167730665 Users should get stats of trips made in the last X timeframe

### PR DESCRIPTION
**Pull request by ChidiChuks**
#### What does this PR do?

Have a user get the counts of trips made within a period

#### Description of Task to be completed?

 - Create a method that counts travel request by time frame
 - Create a route handler
- Implement test-driven development

#### How should this be manually tested?

- Clone the project repository
- Cd into the project repository
- Run `git pull`
- Run `ft-get-trips-timeframe-167730665)`
- Run `npm install`
- Create database `database_name`
- Create `.env` file

#### Screenshots (if appropriate)
image

#### What are the relevant pivotal tracker stories?
[#167730665](https://www.pivotaltracker.com/story/show/167730665)

### CODE REVIEW

**Review by Marshalheri — COMMENTED** [review]
Nice job team mate.
Please i request that you go to your messageUtils.js file and arrange the messages there in an alphabetical order. I did that in the last two PRs that i have raised and i see it has been scattered there.
Also since you have modified the createoneway trip function please rename the **const data** you have there to maybe **const onewayTripData**. The TTL has advised on this before.
Thanks.

**Review by Marshalheri — APPROVED** [review]

**Comment by ChidiChuks** [comment]
> Nice job team mate.
> Please i request that you go to your messageUtils.js file and arrange the messages there in an alphabetical order. I did that in the last two PRs that i have raised and i see it has been scattered there.
> Also since you have modified the createoneway trip function please rename the **const data** you have there to maybe **const onewayTripData**. The TTL has advised on this before.
> Thanks.

Okay @Marshalheri Thanks for the request I will update now. But however, the second request of the `const data` isn't something I will change because it was assigned as a task and I don't think it will be fair enough to change.

**Review by danoseun — APPROVED** [review]
A lot of work has gone into this. Good job bro

**Review by chuksjoe — APPROVED** [review]
Well done bro. just resolve the Hound-CI violation flags

**Comment by ChidiChuks** [comment]
> A lot of work has gone into this. Good job bro

Thanks @danoseun

**Comment by Marshalheri** [comment]
> > Nice job team mate.
> > Please i request that you go to your messageUtils.js file and arrange the messages there in an alphabetical order. I did that in the last two PRs that i have raised and i see it has been scattered there.
> > Also since you have modified the createoneway trip function please rename the **const data** you have there to maybe **const onewayTripData**. The TTL has advised on this before.
> > Thanks.
> 
> Okay @Marshalheri Thanks for the request I will update now. But however, the second request of the `const data` isn't something I will change because it was assigned as a task and I don't think it will be fair enough to change.

he asked me to do it in that chore i did but i forgot so you can just do it its a one line code

**Pull request merged**
