### PR TITLE
#167730617 Sequelize setup and model file

### PR DESCRIPTION
**Pull request by coolbop1**
#### What does this PR do?
Have sequelize configured in the Barefoot Nomad Application
#### Description of Task to be completed?
- Have to use sequlize as our ORM on the API. 
- Set up the migrations and models structure,
#### How should this be manually tested?
Clone the repo, then check for the file called `package.json` to find `sequelize` in the `dependencies`. After, go to the root folder and open a file `.sequelizerc` to find the configuration that created the `boiler plates` of models in the `database` folder.
#### Any background context you want to provide?
- create sequelizerc file to auto generate boiler plates codes
- edit the generated code to work with dotenv config output
#### What are the relevant pivotal tracker stories?
[#167730617](https://www.pivotaltracker.com/story/show/167730617)

### CODE REVIEW

**Comment by ChidiChuks** [comment]
Hopefully, when we install babel-cli...the conflicts thrown by HoundCI will be cleared out. Great job for your progress @coolbop1

**Review by luqmanoop — CHANGES_REQUESTED** [review]
Nice work. You need to pay attention to the codebase folder structure and make sure your `.sequelizerc` config generates files in the appropriate folder.

**Comment by ChidiChuks** [comment]
@coolbop1 Here's what you need to do to get this PR ready for merge

First step:
Delete the [package-lock.json] file from your local machine.

Second step:
write this in your GitBash [git pull origin develop] (from your already created branch for sequelize)

Third step:
run [npm install] on your terminal

Fourth step:
[git add .]

Fifth step:
[git commit -m] 'please use your former commit message here' and [git push]

**Comment by danoseun** [comment]
Hey bro, what's up with this PR?

**Review by chuksjoe — CHANGES_REQUESTED** [review]
Nice work @coolbop1. But I will suggest you use the ES6 standard in `src/database/models/index.js`

**Comment by coolbop1** [comment]
@chuksjoe , thanks , i am working on it .

**Review by chuksjoe — APPROVED** [review]
Well done bro.

**Review by ChidiChuks — APPROVED** [review]
Congratulations @coolbop1. I approve of this. Though you might still need to make little adjustment as we progress in the project.

**Review by Marshalheri — APPROVED** [review]
I have looked through the setup and i think its ok for approval.
Nice work team mate.

**Pull request merged**
